name = input("请输入您的名字")
age = int(input("请输入您的年龄"))
sexxy = input("请输您的的性别")
higt = float(input("请输入您的身高"))
weight = float(input("请输入您的重量"))
ID_number = int(input("请输入您的身份证号"))
education = input("请输入您的学历")
birthday = int(input("请输入您的出生日期"))
amazy = input("请输入你老婆的名字")
addr = input("请输入您的家庭地址")
tel = int(input("请输入您的电话号码"))
case = input("请输入您的职位")
money = int(input("请输入您的薪资"))
print("*"*10)
print("姓名:%s"%name"年龄:%d"%age"性别%s"%sexxy"身高%f"%high"体重%f"%weight"身份证号%d"%Id_number"学历%s"%education"出生日期%d"%birthday"老婆%s"%amazy"家庭住址%s"%addr"电话号码%d"%tel"职位%s"%case"薪资%d"%money)
print("*"*20)

